FORMAT: 1A
HOST: https://api.tago.io

# Tago API
[Markdown](http://daringfireball.net/projects/markdown/syntax) **formatted** description.

<!-- include(account/account.apib) -->
<!-- include(account/analysis.apib) -->
<!-- include(account/buckets.apib) -->
<!-- include(account/data.apib) -->
<!-- include(account/devices.apib) -->
<!-- include(account/dashboard.apib) -->
